Applicant\FacultyBundle\Entity\Institutions:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        site:
            type: string
            length: 255
            nullable: true
        mail:
            type: string
            length: 255
            nullable: true
        director:
            type: string
            length: 255
            nullable: true